name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry
    - name: Install python dependencies
      run: poetry install

    - name: Test
      run: poetry run pytest

    - name: Post matches
      env:
        SLACK_BOT_USER_TOKEN: ${{ secrets.SLACK_BOT_USER_TOKEN }}
        CCB_SKIP_LIST: ${{ secrets.CCB_SKIP_LIST }}
      run: |
        ./scripts/fortnightly.sh
