name: Post

on:
  schedule:
    - cron: '30 3 * * 1'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry

    - name: Install python dependencies
      run: poetry install

    - name: Post matches
      env:
        SLACK_BOT_USER_TOKEN: ${{ secrets.SLACK_BOT_USER_TOKEN }}
      run: |
        poetry run ccb group --output-json=matches.json
        poetry run ccb post --matches-json=matches.json --channel-name=random
